#pragma once

#define AXP_PRIMITIVES_VERSION_MAJOR 1
#define AXP_PRIMITIVES_VERSION_MINOR 0
#define AXP_PRIMITIVES_VERSION_PATCH 0

#define AXP_PRIMITIVES_VERSION \
  (AXP_PRIMITIVES_VERSION_MAJOR * 10000 + AXP_PRIMITIVES_VERSION_MINOR * 100 + AXP_PRIMITIVES_VERSION_PATCH)
